title: Lizhi(Eddie) Zeng
description: The idea of creating a personal website popped up in my mind in mid Nov 2017.</br>I am still working on it.
show_downloads: true
google_analytics: UA-109873000-1
theme: jekyll-theme-minimal