title: Lizhi(Eddie) Zeng
description: Thank you for visiting my page.</br>The idea of creating a personal website popped up in my mind in mid Nov 2017.</br>I am still working on it.
show_downloads: true
google_analytics: 
theme: jekyll-theme-minimal